application: bugs100000000
version: 1
runtime: java
public_root: /root

resource_files:
  - exclude: README.md 
  - exclude: package.json 

builtins:
  - datastore_admin: on

handlers:
  - url: /*
    servlet: org.ringojs.jsgi.JsgiServlet
    name: ringo
    init_params:  
        module-path: src
        config: main
        app: app 
        production: true
        optlevel: 9
        ringo-home: /
